### ISSUE TITLE
Compatibility with FiveM

### ISSUE THREAD

**Issue by NarutoUA** [NarutoUA/gta5_fsr#11]
Currently, mod is incompatible with FiveM. Please don't ask here to add FSR to other games.

**Comment by DeepHunter420** [comment]
will be able to use in five m ? when ? thanks

**Comment by Dennis-NL** [comment]
Allot of players would really like this. Because FiveM can be laggy because of the scripts

**Comment by entspeak** [comment]
FiveM compatibility would be awesome! I primarily play using FiveM.

**Comment by HEisUSdot2dot0** [comment]
> Allot of players would really like this. Because FiveM can be laggy because of the scripts

FSR will not resolve the lag generated by scripts. Those scripts usually relay on RAM and CPU power.

**Comment by glitchygg** [comment]
I await the FiveM support with extreme excitement. Thank you for your hard work

**Comment by DeepHunter420** [comment]
@NarutoUA  any update about five m compatibility ? will be deployed ?

**Comment by Disquse** [comment]
> 
> 
> Allot of players would really like this. Because FiveM can be laggy because of the scripts

I doubt that FSR affects CPU performance so most likely this feature won't help in case of laggy scripts. Server owners should fix their scripts themself. FiveM has all the tools people need to fix script performance.

As was said in this forum topic, FiveM developers are intent to implement FSR support directly into FiveM:
https://forum.cfx.re/t/add-amd-fsr-frame-upscaling-to-client-build/3716526/2?u=disquse

And since ScriptHook support in FiveM is kinda deprecated, I believe the best way to add a FiveM compatibility is direct integration, what do you think about it, @NarutoUA ?

**Comment by NarutoUA** [comment]
> And since ScriptHook support in FiveM is kinda deprecated, I believe the best way to add a FiveM compatibility is direct integration, what do you think about it, @NarutoUA ?

My mod does not require ScriptHook. FiveM support will be added later (maybe today)
